### ISSUE TITLE
Comment tree RID

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-cms#1]
When querying the database for the comments on forum posts, the RID of comments more then 1 level deep is not included. 

As a result, adding sub comments does not function.

**Comment by stevehu** [comment]
It is possible as I never tested it. I am in a process to convert document
schema to vertex and edge. Once done we should have more control on the
relationships. Rid not showing up is a bug and I have seen it before and
found some work around. Let me take a look tonight.

Thanks,

Steve

**Comment by stevehu** [comment]
I tried on my local and you are right. Here is what I got.

result =
[{"id":"1","content":"comment1","parent":"#29:0","children":[{"id":"2","content":"comment2","parent":"#30:0","children":["#30:2"]}]}]

I will remodel it and let you know.

Thanks,

Steve

**Comment by stevehu** [comment]
Do you think if this is going to work?

{
  "id": "1",
  "content": "post1",
  "out_Has": [
    {
      "out": "#11:0",
      "in": {
        "id": "1",
        "content": "Comment1",
        "in_Has": [
          "#13:0"
        ],
        "out_Has": [
          {
            "out": "#12:0",
            "in": {
              "id": "11",
              "content": "Comment11",
              "in_Has": [
                "#13:1"
              ]
            }
          },
          {
            "out": "#12:0",
            "in": {
              "id": "12",
              "content": "Comment12",
              "in_Has": [
                "#13:2"
              ],
              "out_Has": [
                {
                  "out": "#12:3",
                  "in": {
                    "id": "121",
                    "content": "Comment121",
                    "in_Has": [
                      "#13:3"
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    }
  ]
}

**Comment by NicholasAzar** [comment]
Wow this is way different, let me see if I understand it...

So "out" is the parent RID? And is the "in" set of fields representing the comment, where "in_has" is the rid of the post, and "out_has" are the comment children?

That wouldn't match with the values though, shouldn't "in_has"[0] == "out_has"."out"? 

Yeah I think I'm misunderstanding  something here...

Was there a problem with just adding the RID of the comment as a field in the table? I think everything would have been ok in that case. We could have also added a rating number field as well too...

**Comment by stevehu** [comment]
Previously we were using document database and the new output is generated
from graph db. In a long run we should move to graph anyway.

I could not add rid into the resultset as this is a bug. I am still play
with the graph db and generated something similar as document db. I will
send you something tonight.

Thanks,

Steve

**Comment by stevehu** [comment]
how about this one?

{
  "id": "1",
  "content": "post1",
  "out_Has": [
    {
      "id": "1",
      "content": "Comment1",
      "in_Has": [
        "#11:0"
      ],
      "out_Has": [
        {
          "id": "11",
          "content": "Comment11",
          "in_Has": [
            "#12:0"
          ]
        },
        {
          "id": "12",
          "content": "Comment12",
          "in_Has": [
            "#12:0"
          ],
          "out_Has": [
            {
              "id": "121",
              "content": "Comment121",
              "in_Has": [
                "#12:3"
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "2",
      "content": "Comment2",
      "in_Has": [
        "#11:0"
      ]
    }
  ]
}

**Comment by NicholasAzar** [comment]
I think the post will only have an accessible RID if it has a child in this case. Is that right?

**Comment by NicholasAzar** [comment]
Should we just change the add comment rule to use the id of the parent and not the RID? How much would performance suffer?

**Comment by stevehu** [comment]
http://orient-database.narkive.com/89bpEVPT/orientdb-fetchplan-query-does-not-return-ids-in-linked-records

**Comment by NicholasAzar** [comment]
It works!! What a simple solution lol... We can use this temporarily while migrating from document to graph db.
