### ISSUE TITLE
menu component admin cannot be expand on mobile device but user icon can

### ISSUE THREAD

**Issue by stevehu** [networknt/light-cms#5]
Reduce the browser to phone size and hover your mouse cursor over admin, no sub menus. Hover the mouse cursor over person icon, Logout sub menu shows up. Thanks.

**Comment by NicholasAzar** [comment]
Confirmed, admin toggle menu is displaying behind the now vertical menu header... will fix.

**Comment by NicholasAzar** [comment]
Fixed on develop, at your convenience please confirm.

**Comment by stevehu** [comment]
It works in develop branch. Thanks.
